name: getitdone
description: "A Flutter task management application with Firebase and SQLite."

publish_to: 'none' # Keep this if you don't want to publish

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Firebase packages (without exact versions to allow flexibility)
  firebase_core: ^3.6.0
  firebase_auth: any
  cloud_firestore: any
  provider: ^6.0.5
  connectivity_plus: ^4.0.1
  intl: ^0.19.0

  animations: 
  lottie: ^2.2.0
  particles_flutter: ^1.0.1
  flutter_animate: ^4.0.0
  flutter_local_notifications: ^17.2.3
  workmanager: ^0.5.0
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1
  http: ^1.2.2
  timezone: ^0.9.4
  device_info_plus: ^10.1.2
  android_intent_plus: ^5.1.0
  # flutter_native_timezone: ^2.0.0 # Removed
  google_fonts: 
  flutter_svg: 
  url_launcher: ^6.0.20
  googleapis:
  googleapis_auth:
  badges: ^2.0.3
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  linux: true
  image_path: "assets/getitdonelogo.png"