// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vMwcT15BtbI_DK0AW5cTTc0eRXoHzww',
    appId: '1:52920217106:web:233bbe21bd636a7bc2b2cb',
    messagingSenderId: '52920217106',
    projectId: 'getitdone-f0686',
    authDomain: 'getitdone-f0686.firebaseapp.com',
    databaseURL: 'https://getitdone-f0686-default-rtdb.firebaseio.com',
    storageBucket: 'getitdone-f0686.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwVv-AT1M9kYaN9LX4BSgav9qxX5AKQg',
    appId: '1:52920217106:android:1bc6341e139477cbc2b2cb',
    messagingSenderId: '52920217106',
    projectId: 'getitdone-f0686',
    databaseURL: 'https://getitdone-f0686-default-rtdb.firebaseio.com',
    storageBucket: 'getitdone-f0686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeWd8nHVhevcZX2Iyp9aaF-ks7KyY9tAY',
    appId: '1:52920217106:ios:9e960e241cd3eb7dc2b2cb',
    messagingSenderId: '52920217106',
    projectId: 'getitdone-f0686',
    databaseURL: 'https://getitdone-f0686-default-rtdb.firebaseio.com',
    storageBucket: 'getitdone-f0686.appspot.com',
    iosBundleId: 'com.example.getitdone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeWd8nHVhevcZX2Iyp9aaF-ks7KyY9tAY',
    appId: '1:52920217106:ios:9e960e241cd3eb7dc2b2cb',
    messagingSenderId: '52920217106',
    projectId: 'getitdone-f0686',
    databaseURL: 'https://getitdone-f0686-default-rtdb.firebaseio.com',
    storageBucket: 'getitdone-f0686.appspot.com',
    iosBundleId: 'com.example.getitdone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-vMwcT15BtbI_DK0AW5cTTc0eRXoHzww',
    appId: '1:52920217106:web:0c58e937bf0572c0c2b2cb',
    messagingSenderId: '52920217106',
    projectId: 'getitdone-f0686',
    authDomain: 'getitdone-f0686.firebaseapp.com',
    databaseURL: 'https://getitdone-f0686-default-rtdb.firebaseio.com',
    storageBucket: 'getitdone-f0686.appspot.com',
  );
}
